"""created schema

Revision ID: 54867ffd412d
Revises: 
Create Date: 2022-12-12 15:10:33.445505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54867ffd412d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
